### ISSUE TITLE
Setup not working with 0.9.1 and HA 7.3

### ISSUE THREAD

**Issue by sonyboypatrick** [Andre0512/hon#103]
Hello Andre,

I upgraded my Installation to HA 7.3 and your extension to 0.9.1 but I still got the error with "Requirements for hon not found: ['pyhOn==0.14.11']". I tried to reinstall (delete everything and install again) your extension but now I'm not able to set it up again. The flow to input the user data starts but after that I get no feedback and the integration isnt listed.

![image](https://github.com/Andre0512/hon/assets/1961296/e6ea21bb-21b3-4294-b1bc-29c1ca02e63e)

How can I fix it?

BR 
Patrick

**Comment by ilbeppe83** [comment]
Same for me, after the update I receive the same error, and before that the following other notification:

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 12:14:17 (3 occurrences)
Last logged: 12:14:28

Unable to install package pyhOn==0.14.11: ERROR: Cannot install pyhon==0.14.11 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip

**Comment by Andre0512** [comment]
Hey, I created a new version and set the dependencies less strict. 
Please try [`v0.9.2-beta.1`](https://github.com/Andre0512/hon/releases/tag/v0.9.2-beta.1)

**Comment by sonyboypatrick** [comment]
Hey Andre, I dont See an error Message, but the setup is still not working. Nothing happens after entering the login data.

**Comment by N1c093** [comment]
@Andre0512 I just updated to [v0.9.2-beta.1](https://github.com/Andre0512/hon/releases/tag/v0.9.2-beta.1)
Sadly the error still occurs:
```
2023-07-28 11:58:12.523 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package pyhOn==0.14.12: ERROR: Cannot install pyhon==0.14.12 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
2023-07-28 11:58:12.524 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration hon: Requirements for hon not found: ['pyhOn==0.14.12'].
```

**Comment by zhouchang714** [comment]
@Andre0512  the same problem ,Im running Home Assistant 2023.6.1 
`Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 11:33:36 AM (3 occurrences)
Last logged: 11:34:24 AM

Unable to install package pyhOn==0.14.11: ERROR: Cannot install pyhon==0.14.11 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`

**Comment by N1c093** [comment]
I just updated Home Assistant to version `2023.8.0`
With HA `2023.8.0` the custom component hon `0.9.1` is running fine.

**Comment by sonyboypatrick** [comment]
For me its still the same problem after updating. I cant setup the Integration. After entering the login data nothing happens.

**Comment by sonyboypatrick** [comment]
Update: It worked now. I dont know why ... I added a second account and now my main account appeared. I deleted the other one and now everything is fine.
